config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   authenticated :user do
    root 'housings#index', as: :authenticated_root
  end
  root "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :housings do
    resources :rooms, only: [:new, :create]
    resources :rentals, only: [:new, :create]
  end
  resources :rentals, only: [:show] do
    member do
      get :send_email_contract
      get :send_email_inventory
    end

    resources :renters, only: [:new, :create]
    resources :inventories, only: [:new, :create, :index]
    resources :receipts, only: [:new, :create, :index]

    namespace :docusign do
      resource :owner, only: [], controller: :owner do
        member do
          get :signing
          get :docusign_response
        end
      end

      resource :renter, only: [], controller: :renter do
        member do
          get :signing
          get :docusign_response
        end
      end
    end
  end

  resources :receipts, only: [:show]
  resources :rooms, only: [:edit, :update]
  get 'profile/edit', to: 'profiles#edit'
  patch 'profile', to: 'profiles#update'
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  STATES = ["Mauvais", "Moyen", "Bon", "Très bon"]

  belongs_to :rental
  belongs_to :room

  validates :state, presence: true, inclusion: { in: STATES }
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController

  def new
    @rental = Rental.find(params[:rental_id])

    @rental.housing.rooms.each do |room|
      @rental.inventories.new(room: room)
    end
    authorize @rental.inventories.first
  end

  def index
    @rental = Rental.find(params[:rental_id])
    @housing = @rental.housing
    @owner = current_user
    @renter = @rental.renter
    policy_scope @rental.inventories
    respond_to do |format|
    format.html
    format.pdf  {render :pdf => "inventories/index.pdf.erb",
                        :template => 'inventories/index.pdf.erb', formats: :html, encoding: 'utf8'}
    end
  end

  def create
    @rental = Rental.find(params[:rental_id])

    authorize Inventory.new

    if @rental.update(rental_params)
      GenerateInventoryPdfService.new(@rental).call
      redirect_to rental_inventories_path(@rental), notice: 'Votre état des lieux est enregistré.'
    else
      render :new
    end

  end

  private

  def rental_params
    params.require(:rental).permit(inventories_attributes: [:room_id, :state, :observations])
  end

end

app/views/inventories/_form_inventory.html.erb
<%=  simple_form_for @rental, url: rental_inventories_path, method: :post do |f|%>

  <%= f.simple_fields_for :inventories do |field| %>
    <%= field.input :room_id, as: :hidden %>
    <h4 class="mt-5 mb-3"><%= field.object.room.type_of_room %> (<%= field.object.room.size.to_i %> m<sup>2</sup>)</h4>
    <%= field.input :state, {
      as: :radio_buttons,
      label: 'État de la pièce',
      collection: Inventory::STATES,
      class: 'form-check-input',
      wrapper_html: { class: 'form-check form-check-inline' }
      }
    %>
    <%= field.input :observations, label: 'Observations', placeholder: 'Vos commentaires sur la pièce' %>
    <hr class="mt-5">
  <% end %>
  <%= f.submit "Créer mon état des lieux", class: "btn btn-primary btn-lg btn-block" %>
<% end %>

app/views/inventories/_housing_specs.html.erb
<p>Type de logement : <%= @housing.type_of_housing %>.</p>
<p>Surface totale : <%= @housing.size %> m<sup>2</sup>.<p>
<p>Adresse : <%= @housing.street %>, <%= @housing.zip_code %>, <%= @housing.city %>.</p><br>

app/views/inventories/_inventory.html.erb
<h1 class="align-center text-uppercase mt-5">État des lieux</h1>
<p>L’état des lieux doit être établi de façon contradictoire entre les deux parties lors de la remise des clés au locataire et lors de leur restitution en fin de bail. L'état des lieux prévu à l'article 3-2 de la loi du 6 juillet 1989 doit porter sur l'ensemble des locaux et équipements d'usage privatif mentionnés au contrat de bail et dont le locataire a la jouissance exclusive.</p>

<hr class="mt-3 mb-5 d-none">

<h3 class="text-bold mt-5 mb-3">1 - Les locaux</h3>
<div class="card" id="section-1">
  <div class="card-body">
    <p><%= render 'inventories/housing_specs.html.erb', rental: @rental  %></p>
    <hr class="mt-3 mb-5 d-none">
  </div>
</div>

<h3 class="text-bold mt-5 mb-3">2 - Le bailleur</h3>
<div class="card" id="section-2">
  <div class="card-body">
    <p><%= render 'inventories/owner_specs.html.erb', owner: @owner %></p>
    <hr class="mt-3 mb-5 d-none">
  </div>
</div>

<h3 class="text-bold mt-5 mb-3">3 - Le locataire</h3>
<div class="card" id="section-3">
  <div class="card-body">
    <p><%= render 'inventories/renter_specs.html.erb', renter: @renter %></p>
    <hr class="mt-3 mb-5 d-none">
  </div>
</div>

<h3 class="text-bold mt-5 mb-3">4 - Les pièces</h3>
<div class="card" id="section-4">
  <div class="card-body">
    <ul class="list-unstyled">
      <% @rental.inventories.each do |inventory| %>
      <li>
        <%= inventory.room.type_of_room %>
        État : <%= inventory.state %>
        Observations : <%= inventory.observations %>
      </li>
      <% end %>
    </ul>
    <hr class="mt-3 mb-5 d-none">
  </div>
</div>

<h3 class="text-bold mt-5 mb-3">5 - Entretien courant et menues réparations</h3>
<div class="card" id="section-4">
  <div class="card-body">
    <p>Le locataire doit veiller à maintenir en l'état le logement qu'il occupe.
    À ce titre, il doit assurer l'entretien normal du logement et de ses éléments d'équipement, ainsi que les menues réparations nécessaires à moins qu'il ne prouve qu'elles sont dues à la vétusté, à une malfaçon ou à la force majeure.
    À défaut, le bailleur peut retenir sur le dépôt de garantie les sommes correspondant aux réparations
    locatives qui n'ont pas été effectuées par le locataire, justificatifs à l'appui.
    </p>
    <hr class="mt-3 mb-5 d-none">
  </div>
</div>

<p class="mt-5">Fait à (lieu)  , le (date)</p>

app/views/inventories/_owner_specs.html.erb
<p>Nom et prénom : <%= @owner.last_name %> <%= @owner.first_name %></p>
<p>Adresse :</p>
<ul class="list-unstyled">
  <li><%= @owner.street %></li>
  <li><%= @owner.zip_code %></li>
  <li><%= @owner.city %></li>
</ul>

app/views/inventories/_renter_specs.html.erb
<p>Nom et prénom : <%= @renter.last_name %> <%= @renter.first_name %></p>
<p>Coordonnées : tél : <%= @renter.phone_number %>.</p>
<p>email : <%= @renter.email %>.</p>

app/views/inventories/index.html.erb
<div id="inventory-index" class="page-content">
	<div class="container-fluid">
	  <div class="row">

			<!-- Sticky sidebar navigation -->
			<div id="#navbar-sticky" class="col-md-4 housing-index-links">
				<nav class="nav flex-column sticky-top">
					<a class="nav-link" href="#section-1"><h4>Les locaux</h4></a>
					<a class="nav-link" href="#section-2"><h4>Le bailleur</h4></a>
					<a class="nav-link" href="#section-3"><h4>Le locataire</h4></a>
					<a class="nav-link" href="#section-4"><h4>Les pièces</h4></a>
					<a class="nav-link" href="#section-5"><h4>Entretien</h4></a>
				</nav>
			</div>

			<!-- Inventory document -->
      <div class="col-md-7 offset-md-1">
				<div class="row mb-5">
					<div class="col-md-4 align-center">
	          <%= link_to "Revenir au bien", housing_path(@housing), class: "btn btn-outline-primary" %>
					</div>
					<div class="col-md-4 align-center">
						<%= link_to rental_inventories_path(@rental, :format => :pdf), target: :_blank, :target=>'blank', class: "btn btn-primary" do %>
	            <span>PDF</span>
	          <% end %>
					</div>
					<div class="col-md-4 align-center">
						<%= link_to send_email_inventory_rental_path(@rental), remote: true, class: "btn btn-primary" do %>
	            <span>Signer</span>
	          <% end %>
					</div>
	      </div>
        <%= render 'inventory' %>
      </div>


    </div>
  </div>
</div>

app/views/inventories/index.pdf.erb
<%= render :partial => 'inventories/inventory.html.erb' %>

app/views/inventories/new.html.erb
<div class="form-page">
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h3 class="form-title align-center text-bold">Dans quel état est votre bien ?</h3>
        <%= render 'form_inventory', rental: @rental %>
      </div>
    </div>
  </div>
</div>