config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   authenticated :user do
    root 'housings#index', as: :authenticated_root
  end
  root "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :housings do
    resources :rooms, only: [:new, :create]
    resources :rentals, only: [:new, :create]
  end
  resources :rentals, only: [:show] do
    member do
      get :send_email_contract
      get :send_email_inventory
    end

    resources :renters, only: [:new, :create]
    resources :inventories, only: [:new, :create, :index]
    resources :receipts, only: [:new, :create, :index]

    namespace :docusign do
      resource :owner, only: [], controller: :owner do
        member do
          get :signing
          get :docusign_response
        end
      end

      resource :renter, only: [], controller: :renter do
        member do
          get :signing
          get :docusign_response
        end
      end
    end
  end

  resources :receipts, only: [:show]
  resources :rooms, only: [:edit, :update]
  get 'profile/edit', to: 'profiles#edit'
  patch 'profile', to: 'profiles#update'
end

app/views/shared/_banner.html.erb
<!-- Default banner background image for housing#show view -->
<div class="fullscreen fullscreen-img" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.2) 0%, rgba(44,44,44,0.2) 50%), url('https://res.cloudinary.com/bboulesteix/image/upload/v1528029627/housings-background_shrink.jpg')">

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" id="flash" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
  <!-- This line clears the object -->
<% end %>


<% if alert %>
  <div class="alert alert-warning alert-dismissible" id="flash" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
  <!-- This line clears the object -->
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <span>Copyright © Hiry 2018.</span>
</div>

app/views/shared/_navbar.html.erb
<!-- Logo -->
<%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "logo.svg", height: 50 %>
<% end %>

<!-- Right Navigation -->
<div class="navbar-right-container d-none d-md-block">

  <% if user_signed_in? %>

    <!-- Links when logged in -->
    <div class="navbar-wrapper">
      <nav class="navbar-menu navbar-dark">
        <%= link_to "Ajouter un bien", new_housing_path, class: "navbar-item navbar-link bold" %>
        <%= link_to "Voir mes biens", housings_path, class: "navbar-item navbar-link bold" %>
      </nav>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-item">
        <div class="dropdown">
          <%= image_tag current_user.gravatar_url, class: "avatar dropdown-toggle", id: "navbar-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
            <nav>
              <li>
                <%= link_to edit_user_registration_path do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </nav>
          </ul>
        </div>
      </div>
    </div>

  <% else %>
    <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-item navbar-link" %>
  <% end %>

</div>

<!-- Dropdown list appearing on mobile only -->
<div class="navbar-item d-md-none">
  <div class="dropdown">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
      <nav>
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </nav>
    </ul>
  </div>
</div>