config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   authenticated :user do
    root 'housings#index', as: :authenticated_root
  end
  root "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :housings do
    resources :rooms, only: [:new, :create]
    resources :rentals, only: [:new, :create]
  end
  resources :rentals, only: [:show] do
    member do
      get :send_email_contract
      get :send_email_inventory
    end

    resources :renters, only: [:new, :create]
    resources :inventories, only: [:new, :create, :index]
    resources :receipts, only: [:new, :create, :index]

    namespace :docusign do
      resource :owner, only: [], controller: :owner do
        member do
          get :signing
          get :docusign_response
        end
      end

      resource :renter, only: [], controller: :renter do
        member do
          get :signing
          get :docusign_response
        end
      end
    end
  end

  resources :receipts, only: [:show]
  resources :rooms, only: [:edit, :update]
  get 'profile/edit', to: 'profiles#edit'
  patch 'profile', to: 'profiles#update'
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :housing
  has_many :receipts
  has_one :renter
  has_many :inventories

  validates :furnished, default: false
  validates :start_date,       presence: true
  validates :monthly_rent,     presence: true, numericality: { only_integer: true, greater_than: 1,  less_than: 1_000_000 }
  validates :monthly_expenses, presence: true, numericality: { only_integer: true, greater_than: 1,  less_than: 1_000_000 }

  accepts_nested_attributes_for :inventories

  # Carrierwave gem
  mount_uploader :lease_pdf, FileUploader
  mount_uploader :inventory_pdf, FileUploader
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :user_info_completed, only: [ :new ]

  def new
    @housing = Housing.find(params[:housing_id])
    @rental  = Rental.new
    authorize @rental
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.housing = Housing.find(params[:housing_id])
    @housing = @rental.housing
    @rental.renter_token = SecureRandom.hex(10)
    authorize @rental

    if @rental.save
      redirect_to new_rental_renter_path(@rental), notice: 'Location Créée. Veuillez maintenant renseigner les informations sur le locataire.'
    else
      render :new
    end
  end

  def show
    @rental = Rental.find(params[:id])
    @housing = Housing.find(@rental.housing_id)
    @owner = current_user
    @renter = @rental.renter
    authorize @rental
    respond_to do |format|
    format.html
    format.pdf  {render :pdf => "rentals/show.pdf.erb",
                        :template => 'rentals/show.pdf.erb', formats: :html, encoding: 'utf8'}
    end
  end

  def send_email_contract
    @rental = Rental.find(params[:id])
    authorize @rental
    @renter = @rental.renter

    CreateDocusignEnvelopService.new(@rental).call
    UserMailer.contract(@renter).deliver_now
    redirect_to signing_rental_docusign_owner_path(@rental)
  end

  def send_email_inventory
    @rental = Rental.find(params[:id])
    @renter = @rental.renter
    UserMailer.inventory(@renter).deliver_now
  end

  private

  def user_info_completed
    if current_user.street.nil? && current_user.zip_code.nil? && current_user.city.nil? && current_user.phone_number.nil? && current_user.nationality.nil? && current_user.marital_status.nil?
      redirect_to profile_edit_path, notice: "Completer vos infos pour pouvoir créer une location"
      return
    end
  end

  def rental_params
    params.require(:rental).permit(:furnished, :start_date, :end_date, :monthly_rent, :monthly_expenses, :file)
  end
end

app/views/rentals/_details.html.erb
<p>
  Le contrat prendra effet le : <%= rental.start_date %> et prendra fin le :<%= rental.end_date %>
</p>
<ul>
  <li>Loyer mensuel : <%= rental.monthly_rent %> €</li>
  <li>Charges mensuelles : <%= rental.monthly_expenses %> €</li>
</ul>

app/views/rentals/_form_rental.html.erb
<%= simple_form_for [@housing, @rental] do |f| %>
  <%= f.input :furnished, {
    as: :radio_buttons,
    label: 'Type de location',
    collection: ["Meublé", "Non meublé"],
    class: 'form-check-input',
    wrapper_html: { class: 'form-check form-check-inline' }
    }
  %>
  <div class="form-row">
  <%= f.input :start_date, {
    label: 'Date de début de la location',
    as: :string,
    required: false,
    input_html: {class: "datepicker"},
    wrapper_html: { class: 'col-6' }
    }
  %>
  <%= f.input :end_date, {
    label: 'Date de fin (facultatif)',
    as: :string,
    required: false,
    input_html: {class: "datepicker"},
    wrapper_html: { class: 'col-6' }
    }
  %>
</div>
  <div class="form-row">
    <%= f.input :monthly_rent, {
      label:'Loyer mensuel',
      placeholder: '1 350 €',
      wrapper_html: { class: 'col-6' }
      }
    %>
    <%= f.input :monthly_expenses, {
      label:'Charges mensuelles',
      placeholder: '150 €',
      wrapper_html: { class: 'col-6' }
      }
    %>
  </div>
  <%= f.submit "Créer la location", class: "btn btn-primary btn-lg btn-block" %>
<% end %>

app/views/rentals/_housings.html.erb
<ul class="list-unstyled">
  <li>Type de logement : <%= @housing.type_of_housing %></li>
  <li>Régime juridique du bien : <%= @housing.legal_regime %></li>
  <li>Situation : <%= @housing.street %> <%= @housing.zip_code %> <%= @housing.city %></li>
  <li>Période de construction : <%= @housing.year_of_construction %></li>
  <li>Etage : <%= @housing.floor %></li>
  <li>Surface total en m<sup>2</sup> : <%= @housing.size %></li>
</ul>

app/views/rentals/_owners.html.erb
<ul class="list-unstyled">
  <li>Prénom : <%= @owner.first_name %></li>
  <li>Nom : <%= @owner.last_name %></li>
  <li>Rue <%= @owner.street %></li>
  <li>Code postal : <%= @owner.zip_code %></li>
  <li>Ville : <%= @owner.city %></li>
  <li>Nationalité : <%= @owner.nationality %></li>
  <li>Date de naissance : <%= @owner.date_of_birth %></li>
  <li>Statut : <%= @owner.marital_status %></li>
</ul>

app/views/rentals/_rental.html.erb
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<h1 class="align-center text-uppercase mt-5">Contrat de location<br>à usage de résidence principale</h1>
<h4 class="text-gray-dark align-center mt-3">Pour le <%= @housing.street %></h4>
<hr class="mt-3 mb-5">

<h3 class="text-bold mt-5 mb-3">1 - Désignation des parties</h3>
<div class="card" id="section-1">
  <div class="card-body">
    <p>Le présent contrat est conclu entre les soussignés :</p>
    <p><%= render 'rentals/owners.html.erb', rental: @owner %></p>
    <p>Ci-après dénommé « le bailleur ».</p>
    <p>Et</p>
    <p><%= render 'rentals/renters.html.erb', rental: @renter %></p>
    <p>Ci-après dénommé « le locataire ».</p>
    <hr class="mt-3 mb-5 d-none">
  </div>
</div>

<h3 class="text-bold mt-5 mb-3">2 - Objet du contrat</h3>
<div class="card" id="section-2">
  <div class="card-body">
    <p>Le présent contrat a pour objet la location d’un logement ainsi déterminé :  </p>
    <h4>2.a - Consistance du logement </h4>
    <p><%= render 'rentals/housings.html.erb', rental: @housing %></p>
    <br>
    <p>Pièces du logement</p>
    <ul class="list-unstyled">
      <% @housing.rooms.each do |room| %>
        <li>
          <%= room.type_of_room %> : <%= room.size %> <sup>m</sup>2
        </li>
      <% end %>
    </ul>
    <br>
    <h4>2.b - Destination des locaux </h4>
    <p>Résidence principale à usage d'habitation</p>
    <p>Le locataire déclarant connaître les lieux pour les avoir visités et reconnaissant l'existence des éléments ci-dessus énumérés.</p>
    <p>Le logement est loué à titre de résidence principale c’est-à-dire un logement occupé au moins huit mois par an sauf obligation professionnelle, raison de santé ou cas de force majeur, soit par le locataire ou son conjoint, soit par une personne au sens du Code de la Construction et de l’Habitation. Cette condition peut être essentielle dans certains cas pour le bailleur afin de bénéficier de certains avantages fiscaux en matière d'investissement locatif. Ainsi, en cas de non-respect de cette condition, le bailleur pourrait engager la responsabilité contractuelle du preneur.
    </p>
    <br>
    <h4>2.c - Information sur les équipements d’accès aux technologies de l’information et de la communication de l’immeuble </h4>
    <p>L'installation permet l'accès aux services nationaux en clair de télévision par voie hertzienne terrestre en mode numérique. Un réseau de communications électroniques interne à l'immeuble distribue des services de télévision.</p>
    <hr class="mt-3 mb-5 d-none">
  </div>
</div>

<h3 class="text-bold mt-5 mb-3">3 - Date de prise d’effet et durée du contrat </h3>
<div class="card" id="section-3">
  <div class="card-body">
    <h4>3.a — Date de prise d’effet du contrat</h4>
      </p>Le contrat prendra effet le : <%= @rental.start_date %> et prendra fin le : <%= @rental.end_date %></p>
    <br>
    <h4>3.b — Tacite reconduction — Renouvellement</h4>
    <p>A l’expiration du bail, le bailleur ou le locataire pourra mettre en œuvre la procédure de renouvellement conformément à la Loi. A défaut le bail se renouvellera par tacite reconduction. En cas de tacite reconduction, la durée du contrat reconduit est de un an.
    <p>
    Les contrats de locations meublées consenties à un étudiant pour une durée de neuf mois ne sont pas reconduits tacitement à leur terme et le locataire peut mettre fin au bail à tout moment, après avoir donné congé. Le bailleur peut, quant à lui, mettre fin au bail à son échéance et après avoir donné congé.
    </p>
    <h4>3.c — Congé au terme du contrat</h4>
    <p>En respectant un préavis de 3 mois avant l’échéance du contrat ou de son renouvellement, le bailleur peut donner congé. Ce congé devra être fondé soit sur sa décision de reprendre ou de vendre le logement, soit sur un motif légitime et sérieux, notamment l’inexécution par le locataire de l’une des obligations principales lui incombant.
    Le congé devra indiquer le motif allégué :
    En cas de reprise, les nom et adresse du bénéficiaire de la reprise qui ne peut être que l’une des personnes prévues à l’article 15-I de la Loi 25-8 du 6 juillet 1989.
    En cas de vente, le congé pour vente ne vaut pas offre au profit du locataire et ce dernier ne dispose pas de droit de préemption.
    Le congé s'accompagne d'une offre de relogement lorsqu'à la date d'échéance du contrat, le locataire est âgé de plus de soixante-cinq ans et que ses ressources annuelles sont inférieures à un plafond de ressources en vigueur pour l’attribution des logements locatifs conventionnés fixé par arrêté du ministre chargé du logement. Ces dispositions ne s'appliquent néanmoins pas si le bailleur est âgé, à la même date d'échéance du bail, de plus de soixante-cinq ans ou si ses ressources annuelles sont inférieures à un plafond de ressources en vigueur pour l’attribution des logements locatifs conventionnés fixé par arrêté du ministre chargé du logement. La condition d’âge et/ou de ressources est remplie dès lors qu’un seul des bailleurs en satisfait les conditions.
    Dans tous les cas, le congé doit être notifié par lettre recommandée avec demande d'avis de réception, ou signifié par acte d'huissier de justice.
    Si le logement ne constitue pas la résidence principale le bailleur peut se dispenser d’avoir à motiver le congé qu’il délivre.</p>
    <br>
    <h4>3.d — Résiliation par le locataire</h4>
    <p>Le locataire peut résilier le contrat à tout moment, en cours d'exécution ou à son terme, sous réserve de respecter un préavis d’un mois, notifié par lettre recommandée avec accusé de réception, signifié par acte d’huissier ou remis en main propre contre récépissé ou émargement.
    L’obligation de payer les loyers est maintenue jusqu’au terme du bail et ce, même si le locataire libère effectivement les lieux avant la date de départ résultant du congé qu’il a notifié au bailleur, sauf si le logement se trouve occupé avant la fin du préavis par un autre locataire avec l’accord express du bailleur.</p>
    <hr class="mt-3 mb-5 d-none">
  </div>
</div>

<h3 class="text-bold mt-5 mb-3">4 — Conditions financières </h3>
<div class="card" id="section-4">
  <div class="card-body">
    <h4>4.a - Loyer</h4>
    <p>La présente location est consentie et acceptée moyennant un loyer mensuel de <%= @rental.monthly_rent %> € hors charges, payable mensuellement et d'avance le 1ER de chaque mois.
    Le montant des charges s'élèvent à <%= @rental.monthly_expenses %>€</p>
    <br>
    <h4>4.b - Révision Loyer</h4>
    <p>Le loyer ainsi fixé sera révisé chaque année, à la date anniversaire du contrat en fonction de la variation de l'indice de référence des loyers (IRL) publié par l'INSEE ou en fonction de l'indice du taux d'évolution qui lui serait substitué.</p>
    <p>Sur la base du calcul suivant loyer de base X (IRL du trimestre / IRL du trimestre n-1)</p>
    <br>
    <h4>4.c - Charges</h4>
    <p>Le locataire est tenu de payer, en sus du loyer, les charges récupérables telles que définies par l'article 23 de la loi du 6 juillet 1989.</p>
    <p>Le montant des provisions mensuelles sur charges est de : <%= @rental.monthly_expenses %>€</p>
    <br>
    <h4>4.d - Quittance</h4>
    <p>Le loyer se décompose comme suit:</p>
    <ul class="list-unstyled">
      <li><%= @rental.monthly_rent %>€ de loyer</li>
      <li><%= @rental.monthly_expenses %>€ de charges</li>
    </ul>
    <p>Soit un total de <%= @rental.monthly_rent + @rental.monthly_expenses%> €</p>
    <hr class="mt-3 mb-5 d-none">
  </div>
</div>

<h3 class="text-bold mt-5 mb-3">5 — Travaux </h3>
<div class="card" id="section-5">
  <div class="card-body">
    <p>Le locataire ne pourra faire aucune transformation des lieux loués ou des équipements mentionnés au contrat sans l'accord écrit du bailleur. A défaut, le bailleur pourra :
    soit accepter la restitution des locaux tel quel
    soit exiger leur remise en état conformément à l’état des lieux d’entrée
    soit exiger le versement d’une indemnité compensatrice
    Si les transformations mettent en péril le bon fonctionnement des équipements ou la sécurité du local, le bailleur pourra exiger une remise en état immédiate, aux frais du locataire.</p>
    <hr class="mt-3 mb-5 d-none">
  </div>
</div>

<h3 class="text-bold mt-5 mb-3">6 — Clauses résolutoires </h3>
<div class="card" id="section-6">
  <div class="card-body">
    <p>A défaut de paiement au terme convenu, de tout ou partie du loyer ou des charges, ou à défaut de versement du dépôt de garantie, le bail sera résilié de plein droit, deux mois après un commandement de payer demeuré infructueux, sans qu'il soit nécessaire de faire prononcer judiciairement la résolution. Si le locataire refuse de quitter les lieux, il suffira pour l'y contraindre d'une ordonnance de référé.
    De même, à défaut de justification d'une assurance contre les risques locatifs dans les conditions de la loi , ou encore à défaut de respect de l'obligation d'user paisiblement des locaux loués, résultant de troubles de voisinage constatés par une décision de justice passée en force de chose jugée, le bail sera résilié de plein droit un mois après un commandement demeuré infructueux. Si le locataire refuse de quitter les lieux, il suffira pour l'y contraindre d'une ordonnance en référé.</p>
  </div>
</div>
<hr class="mt-3 mb-5 d-none">

<h3 class="text-bold mt-5 mb-3">7 — État des lieux </h3>
<div class="card" id="section-6">
  <div class="card-body">
    <p>Un état des lieux sera dressé contradictoirement entre les parties lors de la remise des clés et de leur restitution. En cas de désaccord sur l’état des lieux, il est établi par huissier à l’initiative de la partie la plus diligente à frais partagés par moitié. L’huissier avise les parties au moins sept jours à l’avance par lettre recommandée avec demande d’avis de réception.
    L'état des lieux établi lors de la mise à disposition des locaux est joint au contrat. Cet état des lieux devra être dressé en autant d’exemplaires que de parties inscrites au bail.
    En cas d’état des lieux incomplet, le locataire peut demander la modification dans un délai de dix jours à compter de son établissement.
    La loi impose aux bailleurs la fourniture d’un détecteur de fumée et la vérification de son bon fonctionnement doit être effectuée lors de l’état des lieux ; l’entretien courant des détecteurs de fumée restant à la charge de l’occupant. Pendant le premier mois de la période de chauffe, le locataire peut demander que l'état des lieux soit complété par l'état des éléments de chauffage.</p>
    <p>Fait à (lieu)  , le (date)</p>
  </div>
</div>

app/views/rentals/_renters.html.erb
<ul class="list-unstyled">
  <li>Prénom : <%= @renter.first_name %></li>
  <li>Nom : <%= @renter.last_name %></li>
  <li>Téléphone : <%= @renter.phone_number %></li>
  <li>email : <%= @renter.email %></li>
  <li>Nationalité : <%= @renter.nationality %></li>
  <li>Date de naissance : <%= @renter.date_of_birth %></li>
  <li>Statut : <%= @renter.marital_status %></li>
</ul>

app/views/rentals/new.html.erb
<div class="form-page">
  <div class="container-fluid">

    <!-- Sidebar showing progression -->
    <div class="row">
      <div class="col-md-3 offset-md-1">
        <aside class="steps-indicator sticky-top">
          <div class="step-section">
            <h5 class="text-uppercase text-bold">Étape 1</h5>
            <h4 class="sans-serif">Votre location</h4>
            <p class="text-gray-dark">Que louez vous, pour combien…</p>
          </div>
          <hr>
          <div class="step-section">
            <h5 class="text-uppercase text-bold text-lighte">Étape 2</h5>
            <h4 class="text-lighter sans-serif">Ajoutez votre locataire</h4>
            <p class="text-gray-dark text-lighter">Ses informations, coordonnées…</p>
          </div>
        </aside>
      </div>

      <!-- Display housing#new form -->
      <div class="col-md-5 offset-md-1">
        <h3 class="form-title align-center bold">Créer une location</h3>
        <%= render 'form_rental', housing: @housing, rental: @rental, renter: @renter %>
      </div>

    <!-- Row ends-->
    </div>

  <!-- Fluid container ends -->
  </div>
</div>

app/views/rentals/show.html.erb
<div id="rental-show" class="page-content">
	<div class="container-fluid">
	  <div class="row">

			<!-- Sticky sidebar navigation -->
			<div id="#navbar-sticky" class="col-md-4 housing-index-links">
				<nav class="nav flex-column sticky-top">
					<a class="nav-link" href="#section-1"><h4>Parties prenantes</h4></a>
					<a class="nav-link" href="#section-2"><h4>Objet du contrat</h4></a>
					<a class="nav-link" href="#section-3"><h4>Dates</h4></a>
					<a class="nav-link" href="#section-4"><h4>Conditions financières</h4></a>
					<a class="nav-link" href="#section-5"><h4>Travaux</h4></a>
					<a class="nav-link" href="#section-6"><h4>Clauses résolutoires</h4></a>
					<a class="nav-link" href="#section-7"><h4>État des lieux </h4></a>
				</nav>
			</div>

			<!-- Rental document -->
      <div class="col-md-7 offset-md-1">
        <div class="row mb-5">
					<div class="col-md-4 align-center">
	          <%= link_to "Revenir au bien", housing_path(@housing), class: "btn btn-outline-primary" %>
					</div>
					<div class="col-md-4 align-center">
	          <%= link_to rental_path(@rental, :format => :pdf), :target=>'blank', class: "btn btn-primary" do %>
	            <span>PDF</span>
	          <% end %>
					</div>
					<div class="col-md-4 align-center">
	          <%= link_to send_email_contract_rental_path(@rental), class: "btn btn-primary" do %>
	            <span>Signer</span>
	          <% end %>
					</div>
        </div>
				<%= render 'rental', housing: @housing %>

        <!-- Show success or not if contract signed -->
				<h3 class="text-bold mt-5">État des signatures</h3>
        <div class="card mt-3">
					<div class="card-body">
          <!-- Signed by owner text -->
	          <% if @rental.signed_by_owner %>
	            <p><i class="fas fa-check-circle text-success"></i>  Vous avez bien signé le contrat de bail<p>
	          <% else %>
	            <p><i class="fas fa-times-circle text-fail"></i>  En attente de votre signature<p>
	          <% end %>

	          <!-- Signed by renter text -->
	          <% if @rental.signed_by_renter %>
	            <p><i class="fas fa-check-circle text-success"></i>  Votre locataire a bien signé le contrat de bail<p>
	          <% else %>
	            <p><i class="far fa-times-circle text-fail"></i>  En attente de la signature de votre locataire<p>
	          <% end %>
					</div>
        </div>

    </div>
  </div>
</div>

app/views/rentals/show.pdf.erb
<%= render :partial => 'rentals/rental.html.erb', rental: @owner %>

<h3>Signature du locataire</h3>
<span style="color:white;">RenterSign</span>
<br><br><br><br>
<h3>Signature du propriétaire</h3>
<span style="color:white;">UserSign</span>