config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   authenticated :user do
    root 'housings#index', as: :authenticated_root
  end
  root "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :housings do
    resources :rooms, only: [:new, :create]
    resources :rentals, only: [:new, :create]
  end
  resources :rentals, only: [:show] do
    member do
      get :send_email_contract
      get :send_email_inventory
    end

    resources :renters, only: [:new, :create]
    resources :inventories, only: [:new, :create, :index]
    resources :receipts, only: [:new, :create, :index]

    namespace :docusign do
      resource :owner, only: [], controller: :owner do
        member do
          get :signing
          get :docusign_response
        end
      end

      resource :renter, only: [], controller: :renter do
        member do
          get :signing
          get :docusign_response
        end
      end
    end
  end

  resources :receipts, only: [:show]
  resources :rooms, only: [:edit, :update]
  get 'profile/edit', to: 'profiles#edit'
  patch 'profile', to: 'profiles#update'
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :rental
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController

  def new
    @rental = Rental.find(params[:rental_id])
    @receipt  = Receipt.new
    authorize @receipt
  end

  def index
    @receipts  = policy_scope(Receipt)
    @rental    = Rental.find(params[:rental_id])
    @receipts  = Receipt.where(rental_id: @rental.id)
    rental_id  = @rental.id
    housing_id = @rental.housing_id
    @housing   = Housing.find(housing_id)
    @renter    = Renter.find_by(rental_id: rental_id)
    @housing   = Housing.find(housing_id)
    user_id    = @housing.user_id
    @user      = User.find(user_id)
  end

  def show
    @receipt   = Receipt.find(params[:id])
    rental_id  = @receipt.rental_id
    @rental    = Rental.find(rental_id)
    housing_id = @rental.housing_id
    @renter    = Renter.find_by(rental_id: rental_id)
    @housing   = Housing.find(housing_id)
    user_id    = @housing.user_id
    @user      = User.find(user_id)
    authorize @receipt
    respond_to do |format|
    format.html
    format.pdf  {render :pdf => "receipts/show.pdf.erb",
                        :template => 'receipts/show.pdf.erb', formats: :html, encoding: 'utf8'}
    end
  end

  def create
    @receipt = Receipt.new(receipt_params)
    @rental = Rental.find(params[:rental_id])
    @receipt.rental = @rental
    @receipt.monthly_invoice = @rental.monthly_rent + @rental.monthly_expenses
    authorize @receipt
    if @receipt.save
      redirect_to  rental_receipts_path(@rental), notice: 'Votre quittance a bien été crée.'
    else
      render :new
    end
  end

  def receipt_params
    params.require(:receipt).permit(:date)
  end
end

app/views/receipts/_form_receipt.html.erb
<%= simple_form_for [@rental, @receipt] do |f| %>
  <%= f.input :date %>
  <%= f.submit "Créer ma quittance", class: "btn btn-primary btn-lg btn-block"%>
<% end %>

app/views/receipts/_receipt.html.erb
<div>
  <div class="text-center full-width-green">
    <strong>QUITTANCE DE LOYER</strong>
  </div>

  <p>Quittance de loyer pour le mois de <%= @receipt.date.strftime("%B, %Y") %></p>

  <div class="black-border">
    <strong><u>Adresse de location</u></strong> <br>
    <%= @housing.street %>, <%= @housing.zip_code %>, <%= @housing.city %>
  </div>

  <br>
  <div class="text-justify">
    Je soussigné <%= @user.gender %><%= @user.first_name %><%= @user.last_name %> propriétaire du logement désigné ci-dessus, déclare avoir reçu de <%= @renter.gender %><%= @renter.first_name %> <%= @renter.last_name %>, la somme de <%= @receipt.monthly_invoice %>, au titre du paiement du loyer et des charges pour la période de location de <%= @receipt.date.strftime("%B, %Y") %> et lui en donne quittance, sous réserve de tous mes droits.
  </div>

  <br>
  <div class="black-border">
    <strong><u>Réglement</u></strong> <br>
    Loyer de <%= @receipt.date.strftime("%B, %Y") %>: <%= @receipt.monthly_invoice %>€
  </div>

</div>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<hr>

<div>
  <small>Cette quittance annule tous les reçus qui auraient pu être établis précédemment en cas de paiement partiel du montant du présent terme. Elle est à conserver pendant trois ans par le locataire (article 7-1 de la loi n° 89-462 du 6 juillet 1989)</small>
</div>

app/views/receipts/index.html.erb
<div id="receipts-index" class="page-content">
	<div class="container">
	  <div class="row">

      	<div class="col-md-8 offset-md-2">
					<div class="align-center">
	        	<%= link_to "Revenir au bien", housing_path(@rental.housing), class: "btn btn-outline-primary mb-5 text-center" %>
					</div>
	        <h1 class="align-center">Mes quittances</h1>

					<!-- Info on the housing & renter -->
	        <% if @renter.nil? %>
	          <div>
	            Vous n'avez pas encore défini de locataire
	          </div>
	        <% else %>
	          <div class="card-date-title align-center" >
	            <h4 class="text-black mb-3"><%= @housing.street %></h4>
							<h5 class="text-gray-alt"><%= @renter.gender %> <%= @renter.first_name %> <%= @renter.last_name %></h5>
	            <p class="text-black"><%= link_to "Contrat de location", rental_path(@rental) %> daté du <%= I18n.localize(@rental.start_date, format: '%e %B %Y') %></p>
	          </div>
	        <% end %>

					<% unless @receipts.present? %>
						<div class="card align-center">
							<div class="card-body my-3">
								<h3 class="card-title serif">Vous n’avez pas encore créé de quittance</h3>
								<p class="card-text">Ajoutez une première quittance pour votre location.</p>
								<%= link_to "Créer une quittance", new_rental_receipt_path(@rental), class: "btn btn-primary btn-lg my-5" %>
							</div>
						</div>
					<% end %>

	        <!-- All receipts -->
					<% if @receipts.present? %>
						<hr class="my-5">
		        <section id="receipt-index">
		          <% receipts_sorted = @receipts.sort_by &:date %>
		          <% receipts_sorted.reverse.each do |receipt| %>
		            <div class="card-receipt my-3">
		              <div class="card-receipt-date">
		                <%= I18n.localize(receipt.date, format: '%B %Y') %>
		              </div>
		              <div class="card-receipt-info">
		                <span>Montant total : <%= receipt.monthly_invoice %> €</span>
		              </div>
		              <div class="card-receipt-edit">
		                <%= link_to receipt_path(receipt, :format => :pdf), target: :_blank do %>
		                  <i class="fa fas fa-print"></i>
		                <% end %>
		              </div>
		            </div>
		          <% end %>
							<%= link_to "Créer une nouvelle quittance", new_rental_receipt_path(@rental), class: "btn btn-primary btn-lg btn-block my-3" %>
		        </section>
					<% end %>

				</div>

    </div>
  </div>
</div>

app/views/receipts/new.html.erb
<div class="form-page">
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h3 class="form-title align-center bold">Créer une quittance de loyer</h3>
        <%= render 'form_receipt', receipt: @receipt %>
      </div>
    </div>
  </div>
</div>

app/views/receipts/show.html.erb
<div class="page-content">
	<div class="container">
	  <div class="row">
      <div class="col-md-8 offset-md-2">
        <%= link_to "Retourner à mon tableau de bord", housing_path(@housing),                class: "btn btn-primary mt-2" %>
        <%= link_to "Retourner à mes quittances", rental_receipts_path(@rental),              class: "btn btn-primary mt-2" %>
        <%= link_to 'Version PDF', receipt_path(@receipt, :format => :pdf), target: :_blank, class: "btn btn-primary mt-2" %>
        <hr>
        <%= render 'receipt' %>
      </div>
    </div>
  </div>
</div>

app/views/receipts/show.pdf.erb
<%= render :partial => 'receipt.html.erb' %>